# 데이터 분석
## 배열(NumPy)
## 데이터프레임(pandas)

In [11]:
# 리스트
lst = list(range(10))
print(lst)
print(lst * 2)

# result = []
# for 변수 in 반복가능객체:
#     result.append(변수 * 2)

result = []
for num in lst:
    result.append(num * 2)    
print(result)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [12]:
import numpy as np
# 배열(NumPy)
arr = np.arange(10)
print(arr)
print(arr * 2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]

In [13]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [15]:
# 결측치 개수 확인
df.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [16]:
print(True + True)
print(True + False)
print(False + False)

2
1
0

In [17]:
# 주요 통계 지표(숫자 타입)
# 개수(count), 평균(mean), 표준편차(std), 최솟값(min), 분위수(25%, 50%, 75%), 최댓값(max)
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [18]:
# 중복값 확인
df.duplicated().sum()

np.int64(1)

In [19]:
df[df.duplicated()]

     total_bill  tip     sex smoker   day   time  size
202        13.0  2.0  Female    Yes  Thur  Lunch     2

In [20]:
# 카테고리 타입의 값 확인
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']

In [ ]:
df.groupby(['smoker']).mean()

TypeError: category dtype does not support aggregation 'mean'